services:
  
  app:
    build: .
    command: ["dev", "bfbc2_masterserver", "--host", "0.0.0.0"]
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - ./bfbc2_masterserver:/app/bfbc2_masterserver
    
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/db
