from enum import Enum


class ErrorCode(Enum):
    SESSION_NOT_AUTHORIZED = 20
    PARAMETERS_ERROR = 21
    NOT_INITIALIZED = 22
    SYSTEM_ERROR = 99
    USER_NOT_FOUND = 101
    TRANSACTION_DATA_NOT_FOUND = 104
    NOT_ENTITLED_TO_GAME = 120
    INVALID_PASSWORD = 122
    ALREADY_REGISTERED = 160
    CODE_ALREADY_USED = 180
    CODE_NOT_FOUND = 181
    TOS_OUT_OF_DATE = 260
    RECORD_NOT_FOUND = 5000
